version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    environment:
      LC_ALL: C.UTF-8
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: sudo apt update
      - run: sudo apt install -y stress
      - run: pip3 install -U pytest pytest-cov --user
      - checkout
      # install
      - run: pip3 install . --user
      # There is no actual test
      - run:
          command: pytest --maxfail=1 --cov stressberry
          working_directory: test
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
