#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import argparse
import time
import sys

import stressberry


def _main():
    # args = _parse_cmd_arguments()

    print('Cooldown...')
    base_temp = stressberry.cooldown()
    print('Base temperature {}°C.'.format(base_temp))

    times, temps, freq = stressberry.stress_cpu(
            num_cpus=4,
            time=30,
            measurement_interval=1,
            )

    print(len(times))
    print(times)
    print(len(temps))
    print(temps)
    print(len(freq))
    print(freq)

    print('Cooldown...')
    base_temp = stressberry.cooldown()
    print('Base temperature {}°C.'.format(base_temp))
    return


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Run stress test for the Raspberry Pi.'
        )
    parser.add_argument(
        '-v', '--version',
        help='display version information',
        action='version',
        version='stressberry {}, Python {}'.format(
            stressberry.__version__, sys.version
            )
        )
    parser.add_argument(
        'outfile',
        nargs='?',
        type=argparse.FileType('w'),
        default=sys.stdout,
        help='output BibTeX file (default: stdout)'
        )
    return parser.parse_args()


if __name__ == '__main__':
    _main()
