#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import argparse
import sys

import stressberry


def _main():
    # args = _parse_cmd_arguments()

    stressberry.start_stressing(1, 10)
    return


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Run stress test for the Raspberry Pi.'
        )
    parser.add_argument(
        '-v', '--version',
        help='display version information',
        action='version',
        version='stressberry {}, Python {}'.format(
            stressberry.__version__, sys.version
            )
        )
    parser.add_argument(
        'outfile',
        nargs='?',
        type=argparse.FileType('w'),
        default=sys.stdout,
        help='output BibTeX file (default: stdout)'
        )
    return parser.parse_args()


if __name__ == '__main__':
    _main()
