name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: 'pip'
    - uses: actions/checkout@v3
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: sudo apt-get install -y stress
    - name: Test with tox
      run: |
        pip install tox
        tox
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version == '3.8' }}
