name: test

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v1
    - name: Lint with flake8
      run: |
        pip install --upgrade pip
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install -y stress
    - name: Install package
      run: |
        pip install --upgrade pip
        pip install .[all]
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        cd test/ && MPLBACKEND=Agg pytest --cov stressberry
    - name: Submit to codecov
      run: bash <(curl -s https://codecov.io/bash)
